export const ADD_AGENT = "ADD_AGENT";
export const RETRIEVE_AGENT = "RETRIEVE_AGENT";
export const UPDATE_AGENT = "UPDATE_AGENT";
export const DELETE_AGENT = "DELETE_AGENT";

export const ADD_PROMPT = "ADD_PROMPT";
export const RETRIEVE_PROMPTS = "RETRIEVE_PROMPTS";
export const UPDATE_PROMPT = "UPDATE_PROMPT";
export const DELETE_PROMPT = "DELETE_PROMPT";

export const ADD_CHAIN = "ADD_CHAIN";
export const RETRIEVE_CHAINS = "RETRIEVE_CHAINS";
export const UPDATE_CHAIN = "UPDATE_CHAIN";
export const DELETE_CHAIN = "DELETE_CHAIN";

export const RETRIEVE_PROVIDER = "RETRIEVE_PROVIDER";
export const RETRIEVE_PROVIDER_BY_NAME = "RETRIEVE_PROVIDER_BY_NAME";

export const RETRIEVE_ENVIRONMENT_STATE = "RETRIEVE_ENVIRONMENT_STATE";
export const UPDATE_ENVIRONMENT_STATE = "UPDATE_ENVIRONMENT_STATE";

export const STORED = "STORED";